version: 2
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    labels:
      - "dependencies"
    groups:
      actions-patch-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      actions-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    labels:
      - "dependencies"
    groups:
      composer-patch-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
